### ISSUE TITLE
計測が失敗しないようにする

### ISSUE THREAD

**Issue by leonard475192** [leonard475192/web-speed-hackathon-2024#16]

**Comment by leonard475192** [comment]
```
HTTPException [Error]: authMiddeware: Unauthorized.
    at /usr/src/app/workspaces/server/dist/server.js:57677:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async dispatch (/usr/src/app/node_modules/.pnpm/hono@4.1.0/node_modules/hono/dist/cjs/compose.js:51:17) {
  res: undefined,
  status: 401,
  [cause]: undefined
}
HTTPException [Error]: authMiddeware: Unauthorized.
    at /usr/src/app/workspaces/server/dist/server.js:57677:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async dispatch (/usr/src/app/node_modules/.pnpm/hono@4.1.0/node_modules/hono/dist/cjs/compose.js:51:17) {
  res: undefined,
  status: 401,
  [cause]: undefined
}
/usr/src/app/workspaces/server:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @wsh-2024/server@ start: `node ./dist/server.js`
Exit status 129
 ELIFECYCLE  Command failed with exit code 1.

```
